version: "3.4"

name: nestapp

services:
  postgres:
    image: postgres:14-alpine
    restart: on-failure
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nest-app-template
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - net
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "sh -c 'pg_isready -U postgres -d postgres'"
        ]
      interval: 10s
      timeout: 3s
      retries: 3

  mongodb:
    image: mongo:6-jammy
    restart: always
    ports:
      - ${MONGODB_PORT}:27017
    volumes:
      - mongodata:/data/db
    networks:
      - net

  redis:
    image: redis:7.2-alpine
    restart: on-failure
    ports:
      - ${REDIS_PORT}:6379
    # command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - redisdata:/data
    networks:
      - net

  adminer:
    image: adminer:4.8.1
    restart: always
    depends_on:
      - postgres
    ports:
      - ${ADMINER_PORT}:8080
    networks:
      - net

  server:
    image: detteksie/nest-app-template
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: unless-stopped
    depends_on:
      - postgres
      - mongodb
      - redis
    ports:
      - 4000:4000
    networks:
      - net
    env_file:
      - .env

volumes:
  pgdata:
  mongodata:
  redisdata:


networks:
  net:
