export const DATABASE_URL = 'DATABASE_URL';
export const MONGODB_URI = 'MONGODB_URI';

export const JWT_ACCESS_SECRET = 'JWT_ACCESS_SECRET';
export const JWT_REFRESH_SECRET = 'JWT_REFRESH_SECRET';
export const JWT_ACCESS_DURATION = 'JWT_ACCESS_DURATION';
export const JWT_REFRESH_DURATION = 'JWT_REFRESH_DURATION';

export const THROTTLE_TTL = 'THROTTLE_TTL';
export const THROTTLE_LIMIT = 'THROTTLE_LIMIT';

export const REDIS_HOST = 'REDIS_HOST';
export const REDIS_PORT = 'REDIS_PORT';
export const REDIS_PASSWORD = 'REDIS_PASSWORD';
export const REDIS_URL = 'REDIS_URL';
export const CACHE_TTL = 'CACHE_TTL';

export const MULTER_DEST = 'MULTER_DEST';
